version: '3.1'
services:
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
