/**
 * Redux Slices Exports
 */

// Auth Slice
export {
  loginAsync,
  registerAsync,
  logoutAsync,
  refreshTokenAsync,
  getCurrentUserAsync,
  checkAuthAsync,
  clearError as clearAuthError,
  setCurrentUser,
  clearAuth,
  selectCurrentUser,
  selectIsAuthenticated,
  selectIsModerator,
  selectAuthLoading,
  selectAuthError,
  selectAuthInitializing,
  selectUserId,
  selectUsername,
  selectUserEmail,
} from './authSlice';

// User Slice
export {
  fetchUsersAsync,
  fetchUserByIdAsync,
  updateUserAsync,
  deleteUserAsync,
  fetchFollowersAsync,
  fetchFollowingAsync,
  followUserAsync,
  unfollowUserAsync,
  fetchFavoriteArtistsAsync,
  fetchFavoriteAlbumsAsync,
  fetchFavoriteSongsAsync,
  fetchUserReviewsAsync,
  clearError as clearUserError,
  clearCurrentProfile,
  addUser,
  removeUser,
  selectUsers,
  selectUserById,
  selectCurrentProfile,
  selectFollowers,
  selectFollowing,
  selectFavoriteArtists,
  selectFavoriteAlbums,
  selectFavoriteSongs,
  selectUserReviews,
  selectUserPagination,
  selectUserReviewsPagination,
  selectUserLoading,
  selectUserError,
  selectLoadingProfile,
  selectLoadingFollowers,
  selectLoadingFollowing,
  selectLoadingFavorites,
  selectLoadingReviews,
} from './userSlice';

// Artist Slice
export {
  fetchArtistsAsync,
  fetchArtistByIdAsync,
  createArtistAsync,
  updateArtistAsync,
  deleteArtistAsync,
  fetchArtistAlbumsAsync,
  fetchArtistSongsAsync,
  fetchArtistReviewsAsync,
  createArtistReviewAsync,
  addArtistFavoriteAsync,
  removeArtistFavoriteAsync,
  clearError as clearArtistError,
  clearCurrentArtist,
  addArtist,
  removeArtist,
  selectArtists,
  selectArtistById,
  selectCurrentArtist,
  selectArtistAlbums,
  selectArtistSongs,
  selectArtistReviews,
  selectArtistPagination,
  selectArtistLoading,
  selectArtistError,
  selectLoadingArtist,
  selectLoadingAlbums,
  selectLoadingSongs,
  selectLoadingReviews as selectLoadingArtistReviews,
} from './artistSlice';

// Album Slice
export {
  fetchAlbumsAsync,
  fetchAlbumByIdAsync,
  createAlbumAsync,
  updateAlbumAsync,
  deleteAlbumAsync,
  fetchAlbumSongsAsync,
  fetchAlbumReviewsAsync,
  createAlbumReviewAsync,
  addAlbumFavoriteAsync,
  removeAlbumFavoriteAsync,
  clearError as clearAlbumError,
  clearCurrentAlbum,
  addAlbum,
  removeAlbum,
  selectAlbums,
  selectAlbumById,
  selectCurrentAlbum,
  selectAlbumSongs,
  selectAlbumReviews,
  selectAlbumPagination,
  selectAlbumLoading,
  selectAlbumError,
  selectLoadingAlbum,
  selectLoadingAlbumSongs,
  selectLoadingAlbumReviews,
} from './albumSlice';

// Song Slice
export {
  fetchSongsAsync,
  fetchSongByIdAsync,
  createSongAsync,
  updateSongAsync,
  deleteSongAsync,
  fetchSongReviewsAsync,
  createSongReviewAsync,
  addSongFavoriteAsync,
  removeSongFavoriteAsync,
  clearError as clearSongError,
  clearCurrentSong,
  addSong,
  removeSong,
  selectSongs,
  selectSongById,
  selectCurrentSong,
  selectSongReviews,
  selectSongPagination,
  selectSongLoading,
  selectSongError,
  selectLoadingSong,
  selectLoadingSongReviews,
} from './songSlice';

// Review Slice
export {
  fetchReviewsAsync,
  fetchReviewByIdAsync,
  createReviewAsync,
  updateReviewAsync,
  deleteReviewAsync,
  fetchReviewLikesAsync,
  likeReviewAsync,
  unlikeReviewAsync,
  fetchReviewCommentsAsync,
  blockReviewAsync,
  unblockReviewAsync,
  clearError as clearReviewError,
  clearCurrentReview,
  addReview,
  removeReview,
  selectReviews,
  selectReviewById,
  selectCurrentReview,
  selectReviewComments,
  selectReviewLikes,
  selectReviewPagination,
  selectReviewLoading,
  selectReviewError,
  selectLoadingReview,
  selectLoadingComments,
  selectLoadingLikes,
} from './reviewSlice';

// Comment Slice
export {
  fetchCommentsAsync,
  fetchCommentByIdAsync,
  createCommentAsync,
  updateCommentAsync,
  deleteCommentAsync,
  clearError as clearCommentError,
  clearCurrentComment,
  addComment,
  removeComment,
  selectComments,
  selectCommentById,
  selectCurrentComment,
  selectCommentPagination,
  selectCommentLoading,
  selectCommentError,
  selectLoadingComment,
} from './commentSlice';

// Notification Slice
export {
  fetchNotificationsAsync,
  // fetchUnreadCountAsync,
  markAsReadAsync,
  markAllAsReadAsync,
  deleteNotificationAsync,
  clearError as clearNotificationError,
  addNotification,
  removeNotification,
  clearAllNotifications,
  selectNotifications,
  selectNotificationById,
  selectNotificationIds,
  selectNotificationList,
  selectUnreadNotifications,
  selectUnreadCount,
  selectNotificationPagination,
  selectNotificationLoading,
  selectNotificationError,
  selectLoadingCount,
} from './notificationSlice';

// Search Slice
// export {
//   searchAsync,
//   searchUsersAsync,
//   searchArtistsAsync,
//   searchAlbumsAsync,
//   searchSongsAsync,
//   searchReviewsAsync,
//   setQuery,
//   setFilters,
//   clearSearch,
//   clearError as clearSearchError,
//   addRecentSearch,
//   clearRecentSearches,
//   selectSearchQuery,
//   selectSearchResults,
//   selectSearchFilters,
//   selectIsSearching,
//   selectSearchError,
//   selectRecentSearches,
//   selectHasResults,
// } from './searchSlice';

// UI Slice
export {
  toggleSidebar,
  setSidebarOpen,
  openModal,
  closeModal,
  showConfirmation,
  hideConfirmation,
  setGlobalLoading,
  addToast,
  removeToast,
  clearAllToasts,
  showSuccess,
  showError,
  showWarning,
  showInfo,
  setFormSubmitting,
  clearFormSubmitting,
  resetUI,
  selectSidebarOpen,
  selectModal,
  selectConfirmationDialog,
  selectGlobalLoading,
  selectToasts,
  selectFormSubmitting,
} from './uiSlice';

