/**
 * Redux Slices Exports
 */

// Auth Slice
export {
  loginAsync,
  registerAsync,
  logoutAsync,
  getCurrentUserAsync,
  checkAuthAsync,
  clearError as clearAuthError,
  setCurrentUser,
  clearAuth,
  selectCurrentUser,
  selectIsAuthenticated,
  selectIsModerator,
  selectAuthLoading,
  selectAuthError,
  selectAuthInitializing,
  selectUserId,
  selectUsername,
  selectUserEmail,
} from './authSlice';

// User Slice
export {
  fetchUsersAsync,
  fetchRecommendedUsersAsync,
  fetchUserByIdAsync,
  updateUserAsync,
  updateUserConfigAsync,
  deleteUserAsync,
  fetchFollowersAsync,
  fetchMoreFollowersAsync,
  fetchFollowingAsync,
  fetchMoreFollowingAsync,
  followUserAsync,
  unfollowUserAsync,
  fetchFavoriteArtistsAsync,
  fetchFavoriteAlbumsAsync,
  fetchFavoriteSongsAsync,
  fetchUserReviewsAsync,
  fetchMoreUserReviewsAsync,
  clearError as clearUserError,
  clearCurrentProfile,
  addUser,
  removeUser,
  selectUsers,
  selectUserById,
  selectCurrentProfile,
  selectFollowers,
  selectFollowing,
  selectFavoriteArtists,
  selectFavoriteAlbums,
  selectFavoriteSongs,
  selectUserReviews,
  selectUserPagination,
  selectFollowersPagination,
  selectFollowingPagination,
  selectUserReviewsPagination,
  selectUserLoading,
  selectUserError,
  selectLoadingProfile,
  selectLoadingFollowers,
  selectLoadingMoreFollowers,
  selectLoadingFollowing,
  selectLoadingMoreFollowing,
  selectLoadingFavorites,
  selectLoadingReviews,
  selectLoadingMoreReviews,
  selectFollowersHasMore,
  selectFollowingHasMore,
  selectUserReviewsHasMore,
} from './userSlice';

// Artist Slice
export {
  fetchArtistsAsync,
  fetchMoreArtistsAsync,
  fetchArtistByIdAsync,
  createArtistAsync,
  updateArtistAsync,
  deleteArtistAsync,
  fetchArtistAlbumsAsync,
  fetchArtistSongsAsync,
  fetchArtistReviewsAsync,
  fetchMoreArtistReviewsAsync,
  fetchUserArtistReviewAsync,
  createArtistReviewAsync,
  addArtistFavoriteAsync,
  removeArtistFavoriteAsync,
  clearError as clearArtistError,
  clearCurrentArtist,
  clearArtists,
  addArtist,
  removeArtist,
  selectArtists,
  selectOrderedArtists,
  selectArtistById,
  selectCurrentArtist,
  selectArtistAlbums,
  selectArtistSongs,
  selectArtistReviews,
  selectArtistPagination,
  selectArtistReviewsPagination,
  selectArtistLoading,
  selectArtistLoadingMore,
  selectArtistError,
  selectLoadingArtist,
  selectLoadingAlbums,
  selectLoadingSongs,
  selectLoadingReviews as selectLoadingArtistReviews,
  selectLoadingMoreArtistReviews,
  selectArtistsHasMore,
  selectArtistReviewsHasMore,
  selectCurrentUserArtistReview,
} from './artistSlice';

// Album Slice
export {
  fetchAlbumsAsync,
  fetchMoreAlbumsAsync,
  fetchAlbumByIdAsync,
  createAlbumAsync,
  updateAlbumAsync,
  deleteAlbumAsync,
  fetchAlbumSongsAsync,
  fetchAlbumReviewsAsync,
  fetchMoreAlbumReviewsAsync,
  fetchUserAlbumReviewAsync,
  createAlbumReviewAsync,
  addAlbumFavoriteAsync,
  removeAlbumFavoriteAsync,
  clearError as clearAlbumError,
  clearCurrentAlbum,
  clearAlbums,
  addAlbum,
  removeAlbum,
  selectAlbums,
  selectOrderedAlbums,
  selectAlbumById,
  selectCurrentAlbum,
  selectAlbumSongs,
  selectAlbumReviews,
  selectAlbumPagination,
  selectAlbumReviewsPagination,
  selectAlbumLoading,
  selectAlbumLoadingMore,
  selectAlbumError,
  selectLoadingAlbum,
  selectLoadingAlbumSongs,
  selectLoadingAlbumReviews,
  selectLoadingMoreAlbumReviews,
  selectAlbumsHasMore,
  selectAlbumReviewsHasMore,
  selectCurrentUserAlbumReview,
} from './albumSlice';

// Song Slice
export {
  fetchSongsAsync,
  fetchMoreSongsAsync,
  fetchSongByIdAsync,
  createSongAsync,
  updateSongAsync,
  deleteSongAsync,
  fetchSongReviewsAsync,
  fetchMoreSongReviewsAsync,
  fetchUserSongReviewAsync,
  createSongReviewAsync,
  addSongFavoriteAsync,
  removeSongFavoriteAsync,
  clearError as clearSongError,
  clearCurrentSong,
  clearSongs,
  addSong,
  removeSong,
  selectSongs,
  selectOrderedSongs,
  selectSongById,
  selectCurrentSong,
  selectSongReviews,
  selectSongPagination,
  selectSongReviewsPagination,
  selectSongLoading,
  selectSongLoadingMore,
  selectSongError,
  selectLoadingSong,
  selectLoadingSongReviews,
  selectLoadingMoreSongReviews,
  selectSongsHasMore,
  selectSongReviewsHasMore,
  selectCurrentUserSongReview,
} from './songSlice';

// Review Slice
export {
  fetchReviewsAsync,
  fetchMoreReviewsAsync,
  fetchFollowingReviewsAsync,
  fetchMoreFollowingReviewsAsync,
  fetchReviewByIdAsync,
  createReviewAsync,
  updateReviewAsync,
  deleteReviewAsync,
  fetchReviewLikesAsync,
  fetchMoreReviewLikesAsync,
  likeReviewAsync,
  unlikeReviewAsync,
  fetchReviewLikedStatusAsync,
  fetchReviewCommentsAsync,
  fetchMoreReviewCommentsAsync,
  deleteCommentAsync,
  postCommentAsync,
  blockReviewAsync,
  unblockReviewAsync,
  clearError as clearReviewError,
  clearCurrentReview,
  clearReviews,
  addReview,
  removeReview,
  selectReviews,
  selectOrderedReviews,
  selectReviewById,
  selectCurrentReview,
  selectReviewComments,
  selectReviewLikes,
  selectReviewPagination,
  selectReviewLoading,
  selectReviewLoadingMore,
  selectReviewError,
  selectLoadingReview,
  selectLoadingComments,
  selectLoadingMoreComments,
  selectLoadingLikes,
  selectLoadingMoreLikes,
  selectCommentsPagination,
  selectLikesPagination,
  selectReviewsHasMore,
  selectCommentsHasMore,
  selectLikesHasMore,
} from './reviewSlice';

// Notification Slice
export {
  fetchNotificationsAsync,
  fetchMoreNotificationsAsync,
  fetchUnreadCountAsync,
  markAsReadAsync,
  markAllAsReadAsync,
  deleteNotificationAsync,
  clearError as clearNotificationError,
  addNotification,
  removeNotification,
  clearAllNotifications,
  selectNotifications,
  selectNotificationById,
  selectNotificationIds,
  selectOrderedNotifications,
  selectUnreadNotifications,
  selectUnreadCount,
  selectNotificationPagination,
  selectNotificationLoading,
  selectNotificationLoadingMore,
  selectNotificationError,
  selectLoadingCount,
  selectNotificationsHasMore,
} from './notificationSlice';

// UI Slice
export {
  toggleSidebar,
  setSidebarOpen,
  openModal,
  closeModal,
  showConfirmation,
  hideConfirmation,
  setGlobalLoading,
  addToast,
  removeToast,
  clearAllToasts,
  showSuccess,
  showError,
  showWarning,
  showInfo,
  setFormSubmitting,
  clearFormSubmitting,
  resetUI,
  selectSidebarOpen,
  selectModal,
  selectConfirmationDialog,
  selectGlobalLoading,
  selectToasts,
  selectFormSubmitting,
} from './uiSlice';

