app.url.base=http://pawserver.it.itba.edu.ar/paw-2024b-02
app.frontend=http://localhost:3000
app.backend=http://localhost:8080/api


database.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
database.username=paw-2024b-02
database.password=paw-2024b-02

# JWT Configuration
jwt.secret=a-string-secret-at-least-256-bits-long
jwt.access.expiration=900000
jwt.refresh.expiration=2592000000

# Mailing
mailer.host=smtp.gmail.com
mailer.port=25
mailer.email=info.musicboxd@gmail.com
mailer.password=nftppqdwzeioeduc