app.url.base=http://pawserver.it.itba.edu.ar/paw-2024b-02

database.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
database.username=root
database.password=root

# JWT Configuration
jwt.secret=${JWT_SECRET:defaultSecretKeyForDevelopmentOnlyChangeInProduction}
jwt.access.expiration=900000
jwt.refresh.expiration=2592000000

# Mailing
mailer.host=smtp.gmail.com
mailer.port=25
mailer.email=info.musicboxd@gmail.com
mailer.password=nftppqdwzeioeduc