app.url.base=http://localhost:8080/webapp_war

database.url=jdbc:postgresql://localhost:5432/postgres
database.username=root
database.password=root

# Mailing
mailer.host=smtp.gmail.com
mailer.port=25

mailer.email=info.musicboxd@gmail.com
mailer.password=nftppqdwzeioeduc

