app.url.base=http://pawserver.it.itba.edu.ar/paw-2024b-02

database.url=jdbc:postgresql://localhost:5432/postgres
database.username=postgres
database.password=postgres

# Mailing
mailer.host=smtp.gmail.com
mailer.port=25

mailer.email=info.musicboxd@gmail.com
mailer.password=nftppqdwzeioeduc

