app.url.base=http://pawserver.it.itba.edu.ar/paw-2024b-02

database.url=jdbc:postgresql://localhost:5432/paw-2024b-02
database.username=paw-2024b-02
database.password=xBanzuL99

# Mailing
mailer.host=smtp.gmail.com
mailer.port=25

mailer.email=info.musicboxd@gmail.com
mailer.password=nftppqdwzeioeduc

